basePath: /
definitions:
  controllers.email:
    properties:
      email:
        type: string
    type: object
  dto.AuthLogin:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.AuthRegister:
    properties:
      confPass:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phoneNumber:
        type: string
    required:
    - confPass
    - email
    - name
    - password
    - phoneNumber
    type: object
  dto.AuthResetPass:
    properties:
      confPass:
        type: string
      email:
        type: string
      newPass:
        type: string
      otp:
        type: string
    type: object
  utils.Response:
    properties:
      errors: {}
      message:
        type: string
      pageInfo: {}
      results: {}
      success:
        type: boolean
    type: object
  utils.ResponseUser:
    properties:
      email:
        type: string
      name:
        type: string
      phoneNumber:
        type: string
    type: object
info:
  contact: {}
  description: CRUD Swagger
  title: CRUD
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.AuthLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      tags:
      - Auth
  /auth/pass:
    patch:
      consumes:
      - application/json
      description: Reset Pass
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.AuthResetPass'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      tags:
      - Auth
    post:
      consumes:
      - application/json
      description: Forgot Pass
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controllers.email'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.AuthRegister'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utils.ResponseUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      tags:
      - Auth
swagger: "2.0"
